### ISSUE TITLE
GCS deploy using vagrant is failing at "Wait for csi-provisioner to become available"

### ISSUE THREAD

**Issue by PrasadDesala** [gluster/gcs#101]
GCS deploy using vagrant is failing at "Wait for csi-provisioner to become available".

TASK [GCS | CSI Driver | Wait for csi-provisioner to become available] *********
Monday 07 January 2019  12:37:01 +0530 (0:00:01.177)       0:22:30.586 ******** 
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (50 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (49 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (48 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (47 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (46 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (45 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (44 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (43 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (42 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (41 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (40 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (39 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (38 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (37 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (36 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (35 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (34 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (33 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (32 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (31 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (30 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (29 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (28 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (27 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (26 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (25 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (24 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (23 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (22 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (21 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (20 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (19 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (18 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (17 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (16 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (15 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (14 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (13 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (12 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (11 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (10 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (9 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (8 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (7 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (6 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (5 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (4 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (3 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (2 retries left).
FAILED - RETRYING: GCS | CSI Driver | Wait for csi-provisioner to become available (1 retries left).
fatal: [kube1]: FAILED! => {"attempts": 50, "changed": true, "cmd": ["/usr/local/bin/kubectl", "-ngcs", "-ojsonpath={.status.readyReplicas}", "get", "statefulset", "csi-provisioner-glusterfsplugin"], "delta": "0:00:00.225757", "end": "2019-01-07 07:15:53.051966", "rc": 0, "start": "2019-01-07 07:15:52.826209", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/root/prasad/GCS-Prasad/deploy/vagrant-playbook.retry

PLAY RECAP *********************************************************************
kube1                      : ok=393  changed=114  unreachable=0    failed=1   
kube2                      : ok=293  changed=91   unreachable=0    failed=0   
kube3                      : ok=253  changed=71   unreachable=0    failed=0   

Monday 07 January 2019  12:45:53 +0530 (0:08:51.591)       0:31:22.177 ******** 
=============================================================================== 
GCS | CSI Driver | Wait for csi-provisioner to become available ------- 531.59s
GCS | GD2 Cluster | Wait for glusterd2-cluster to become ready -------- 232.65s
Install packages ------------------------------------------------------ 171.98s
GCS | ETCD Cluster | Wait for etcd-cluster to become ready ------------ 154.25s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 52.94s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 46.11s
download : file_download | Download item ------------------------------- 39.73s
kubernetes/master : Master | wait for the apiserver to be running ------ 33.46s
GCS | ETCD Operator | Wait for etcd-operator to be available ----------- 32.35s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 24.09s
etcd : Gen_certs | Write etcd master certs ----------------------------- 20.45s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 16.76s
Wait for host to be available ------------------------------------------ 16.12s
GCS Pre | Manifests | Sync GCS manifests ------------------------------- 13.19s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 13.07s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 12.00s
etcd : reload etcd ----------------------------------------------------- 10.70s
docker : Docker | pause while Docker restarts -------------------------- 10.19s
download : container_download | Download containers if pull is required or told to always pull (all nodes) --- 9.82s
etcd : wait for etcd up ------------------------------------------------- 7.58s
==> kube3: An error occurred. The error will be shown after all tasks complete.
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

An error occurred while executing the action on the 'kube3'
machine. Please handle this error then try again:

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by Madhu-1** [comment]
Fixed in #77
