### ISSUE TITLE
kubectl commands are failing with error "The connection to the server localhost:8080 was refused - did you specify the right host or port?" after successful deploy of gcs using vagrant

### ISSUE THREAD

**Issue by PrasadDesala** [gluster/gcs#103]
kubectl commands are failing with error "The connection to the server localhost:8080 was refused - did you specify the right host or port?" after successful deploy of gcs using vagrant.

<snip/>

onday 07 January 2019  14:55:05 +0530 (0:00:00.541)       0:33:32.113 ******** 
=============================================================================== 
Install packages ------------------------------------------------------ 337.60s
download : file_download | Download item ------------------------------ 235.63s
GCS | GD2 Cluster | Add devices | Add devices for kube1 --------------- 136.36s
GCS | ETCD Cluster | Wait for etcd-cluster to become ready ------------ 114.47s
download : container_download | download images for kubeadm config images -- 93.55s
GCS | CSI Driver | Wait for csi-provisioner to become available -------- 74.54s
GCS | GD2 Cluster | Wait for glusterd2-cluster to become ready --------- 58.57s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 46.52s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 44.44s
GCS | ETCD Operator | Wait for etcd-operator to be available ----------- 42.86s
GCS | Prometheus Operator | Wait for the Prometheus Operator to become ready -- 32.41s
download : file_download | Download item ------------------------------- 32.40s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 31.95s
kubernetes/master : kubeadm | Initialize first master ------------------ 29.74s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 27.63s
kubernetes/master : kubeadm | Init other uninitialized masters --------- 27.35s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 21.10s
etcd : Gen_certs | Write etcd master certs ----------------------------- 20.53s
download : container_download | Download containers if pull is required or told to always pull (all nodes) -- 17.88s
Wait for host to be available ------------------------------------------ 16.18s
(gcs-venv) [root@rhsqa-virt05 deploy]# 
(gcs-venv) [root@rhsqa-virt05 deploy]# 
(gcs-venv) [root@rhsqa-virt05 deploy]# vagrant 
(gcs-venv) [root@rhsqa-virt05 deploy]# vagrant ssh kube1
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ 
[vagrant@kube1 ~]$ kubectl -n gcs get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[vagrant@kube1 ~]$ kubectl -n gcs get pods
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by Madhu-1** [comment]
workaround 

```
[vagrant@kube1 ~]$ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
[vagrant@kube1 ~]$ sudo chown $(id -u):$(id -g) $HOME/.kube/config
[vagrant@kube1 ~]$ kubectl --kubeconfig=$HOME/.kube/config get po
No resources found.
```

**Comment by PrasadDesala** [comment]
> workaround
> 
> ```

Run this steps prior running below steps  
mkdir -p $HOME/.kube

> [vagrant@kube1 ~]$ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
> [vagrant@kube1 ~]$ sudo chown $(id -u):$(id -g) $HOME/.kube/config
> [vagrant@kube1 ~]$ kubectl  get po
> No resources found.
> ```

**Comment by Madhu-1** [comment]
this is because  `--insecure-port=8080 ` and `--insecure-bind-address=127.0.0.1`  are not there in kube-apiserver configuration.

is this removed in  kubespray which we are using?

@JohnStrunk ^^

**Comment by JohnStrunk** [comment]
This issue was opened around the same time the update to 1.13 happened, so I suppose it could be a result of kubrspray changes.

**Comment by atinmu** [comment]
@Madhu-1 This is currently marked for GCS 1.0. If this doesn't get fixed, can we please ensure we have this step mentioned in the deployment section?

**Comment by Madhu-1** [comment]
@atinmu let me update the kubespray version and check , if its not fixed i will add this steps to readme
