### ISSUE TITLE
GCS deployment guide

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/gcs#117]
*(Brought up in 2019-01-10 architecture call)*

For GCS 1.0, we need to have some sort of deployment guide
- How to get it up and running
- How to use it
  - Storage class, PVC, PV
  - Monitoring/dashboard
- Limitations

**Comment by atinmu** [comment]
This is fixed through https://github.com/gluster/gcs/pull/123. A wide part of it will be covered in the gcs website anyways.
