### ISSUE TITLE
Change in README is required

### ISSUE THREAD

**Issue by umangachapagain** [gluster/gcs#121]
https://github.com/gluster/gcs/commit/01f59bb2e1558fb0ddf8eace6346685870840931 provides Prometheus Rules, Alerts and Gluster specific Grafana Dashboards via `gluster-mixins`. 

So, changes is required in the respective [readme](https://github.com/gluster/gcs/tree/master/deploy#accessing-prometheus-ui-and-grafana-dashboard-to-view-the-metrics) section to document the added feature and reduce the manual effort required.

**Comment by atinmu** [comment]
Who is working on this? This is currently marked as blocker for GCS 1.0.

**Comment by umangachapagain** [comment]
> Who is working on this? This is currently marked as blocker for GCS 1.0.

@sidharthanup Are you taking this up?
