### ISSUE TITLE
Issue with deploy-gcs.yml

### ISSUE THREAD

**Issue by vpandey-RH** [gluster/gcs#147]
When deploying GCS using deploy-gcs.yml playbook, have come across this error -

![screenshot from 2019-03-06 14-46-14](https://user-images.githubusercontent.com/33927873/53869717-c2a06980-401e-11e9-844f-6c79c3743895.png)

The kube cluster seems to be working fine.

Is it something to do with the ansible version ? 

Current ansible version - 

`[root@kube1 ~]# ansible --version
ansible 2.7.8
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]`

**Comment by cloudbehl** [comment]
@vpandey-RH After cloning gcs. Try running the commands mentioned below. Then run the playbook. It should work.

```
cd gcs/deploy
git submodule init
git submodule update
```

**Comment by vpandey-RH** [comment]
@cloudbehl  Tried this once before, didn't seem to work. But will try again.

**Comment by vpandey-RH** [comment]
@cloudbehl  Thanks for the solution, seems to be working fine now.

**Comment by kotreshhr** [comment]
Closing the issue as it worked following [comment](https://github.com/gluster/gcs/issues/147#issuecomment-470035773)
