### ISSUE TITLE
glustercli commands are failing on gd2 containers

### ISSUE THREAD

**Issue by rmadaka** [gluster/gcs#17]
1) Created gcs setup with latest  repo.using vagrant
2) once setup is up, all pods are running successfully
3) Then i have logged in to one of the gd2 container.
4) If i try to perform glustercli commands failing with below errors.

[root@kube1-0 /]# glustercli peer status
Failed to get Peers list

Failed to connect to glusterd. Please check if
- Glusterd is running(http://127.0.0.1:24007) and reachable from this node.
- Make sure Endpoints specified in the command is valid

5) Actually glusterd2 services are running on gd2 container.

```[root@kube1-0 /]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/glusterd2.service.d
           └─override.conf
   Active: active (running) since Tue 2018-10-09 13:07:30 UTC; 31min ago
 Main PID: 21 (glusterd2)
   CGroup: /kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podc2de0d59_cbc3_11e8_8128_525400f652d0.slice/docker-a1f24ec1df72f23c60ddce138de88f38fe484febdcf3a41f710ac7461a88936a.scope/system.slice/glusterd2.service
           └─21 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml

Oct 09 13:07:30 kube1-0 systemd[1]: Started GlusterD2, the management service for GlusterFS (pre-release).
Oct 09 13:07:30 kube1-0 systemd[1]: Starting GlusterD2, the management service for GlusterFS (pre-release)...
```

**Comment by rmadaka** [comment]
Found below errors from logs:

time="2018-10-09 13:04:39.643145" level=warning msg="could not read store config file, continuing with defaults" error="open /var/lib/glusterd2/store.toml: no such file or directory" source="[config.go:128:store.GetConfig]"
time="2018-10-09 13:04:44.648826" level=error msg="failed to start embedded store" error="context deadline exceeded" source="[embed.go:36:store.newEmbedStore]"
time="2018-10-09 13:04:44.648889" level=fatal msg="Failed to initialize store (etcd client)" error="context deadline exceeded" source="[main.go:101:main.main]"

It seems some failures with etcd client.

**Comment by amarts** [comment]
> you need to pass --endpoints argument to the glustercli command

Can we fix this in documentation?
