### ISSUE TITLE
ETCD pods not getting spin automatically

### ISSUE THREAD

**Issue by rmadaka** [gluster/gcs#29]
If we delete the etcd pod manually, new etcd pod not getting created automatically.  I think etcd operator pod not taking care of etcd pods.

**Comment by rmadaka** [comment]
If we delete the one etcd pod manually out of 3 etcd pods , new etcd pod not getting created automatically and Remaining 2 etcd pods went to completed state.

For 3 node etcd cluster , if any one of the etcd pod went to bad state. Remaining two etcd pods should be able to take care of gcs cluster. But here that is not happening.

**Comment by kshlm** [comment]
Same as #15.
