### ISSUE TITLE
vagrant up throws error - centos/atomic-host could not be found

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [gluster/gcs#32]
deploy$ vagrant up 
> Bringing machine 'kube1' up with 'libvirt' provider...
> Bringing machine 'kube2' up with 'libvirt' provider...
> Bringing machine 'kube3' up with 'libvirt' provider...
> ==> kube3: An error occurred. The error will be shown after all tasks complete.
> ==> kube2: Box 'centos/atomic-host' could not be found. Attempting to find and install...
>     kube2: Box Provider: libvirt
>     kube2: Box Version: >= 0
> ==> kube1: Box 'centos/atomic-host' could not be found. Attempting to find and install...
>     kube1: Box Provider: libvirt
>     kube1: Box Version: >= 0
> ==> kube2: An error occurred. The error will be shown after all tasks complete.
> ==> kube1: An error occurred. The error will be shown after all tasks complete.
> An error occurred while executing multiple actions in parallel.
> Any errors that occurred are shown below.
> 
> An error occurred while executing the action on the 'kube1'
> machine. Please handle this error then try again:
> 
> The box 'centos/atomic-host' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/centos/atomic-host"]
> Error: The requested URL returned error: 404
> 
> An error occurred while executing the action on the 'kube2'
> machine. Please handle this error then try again:
> 
> The box 'centos/atomic-host' could not be found or
> could not be accessed in the remote catalog. If this is a private
> box on HashiCorp's Atlas, please verify you're logged in via
> `vagrant login`. Also, please double-check the name. The expanded
> URL and error message are shown below:
> 
> URL: ["https://atlas.hashicorp.com/centos/atomic-host"]
> Error: The requested URL returned error: 404
> 
> An error occurred while executing the action on the 'kube3'
> machine. Please handle this error then try again:
> 
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> ansible remote provisioner:
> * The following settings shouldn't exist: become
> 
> 
>

**Comment by JohnStrunk** [comment]
Perhaps try fetching the vagrant image manually:
```
$ vagrant box add centos/atomic-host
==> box: Loading metadata for box 'centos/atomic-host'
    box: URL: https://vagrantcloud.com/centos/atomic-host
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) libvirt
2) virtualbox

Enter your choice: 1
==> box: Adding box 'centos/atomic-host' (v1808.01) for provider: libvirt
    box: Downloading: https://vagrantcloud.com/centos/boxes/atomic-host/versions/1808.01/providers/libvirt.box
    box: Download redirected to host: cloud.centos.org
==> box: Successfully added box 'centos/atomic-host' (v1808.01) for 'libvirt'!
$ vagrant box list
...
centos/atomic-host    (libvirt, 1808.01)
...
```

If you continue to have errors, please provide:
```
$ vagrant version
$ ansible --version
```

**Comment by SaravanaStorageNetwork** [comment]
> 
> $ vagrant --version 
> Vagrant 1.8.1
> 
> $ ansible --version
> ansible 2.3.1.0
>   config file = /home/sarumuga/workspace/projects/gluster/repos/gerrit_gluster/gcs_all/gcs/deploy/ansible.cfg
>   configured module search path = [u'./kubespray/library']
>   python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
> 


I think issue is most likely with my older fedora system
I will check this in another system and update.

**Comment by SaravanaStorageNetwork** [comment]
Update:

Tried with latest vagrant , it failed.
vagrant --version 
Vagrant 2.1.5

But with vagrant 2.0.2 in Fedora 27 it worked fine. 
Thanks!
