### ISSUE TITLE
Sometimes prepare.sh script is failing

### ISSUE THREAD

**Issue by rmadaka** [gluster/gcs#42]
1) git clone https://github.com/gluster/gcs gcs-8
2) Under gcs-8 directory, create one more directory 'dir1'
3) Then copy data from deploy directory, cp -r deploy/* dir1/
4) Then run ./prepare.sh
```
[root@rhsqa-virt05 rajesh-76]# ./prepare.sh 
vagrant and vagrant-libvirt were found.
For easier operation, ensure that libvirt has been configured to work without passwords.
Ref: https://developer.fedoraproject.org/tools/vagrant/vagrant-libvirt.html

Ensuring kubespray is present
Creating a python virtualenv gcs-venv
Installing requirements into gcs-venv
 **Could not open requirements file: [Errno 2] No such file or directory: './kubespray/requirements.txt'**

Virtualenv gcs-venv has been created
The virtualenv needs to be activated before doing any operations. Operations may fail if virtualenv is not activated.

To activate the virutalenv, run:
$ source gcs-venv/bin/activate
(gcs-venv) $

To deactivate an activated virtualenv, run:
(gcs-venv) $ deactivate
$ 

Note: The virtualenv should be activated for each shell session individually.
```
Mostly i found that once repo is cloned , if we copy data from deploy directory to new directory for first time  then only we are facing this issue, second time onwards we are not facing this issue.

**Comment by kshlm** [comment]
You need to ensure the kubespray submodule is also cloned, before you copy.

`deploy/kubespray` is a git-submodule that by default is present as an empty directory. So if you just copy the deploy directory immediately after clone, kubespray will not be present. This leads to the issue.

prepare.sh, when run from the original deploy directory will download the submodule using git. But it cannot download the submodules into a copy of the deploy directory.

You have two options now. Either,

- Ensure you run prepare.sh once before you create a copy of the deploy directory. The prepare.sh script fetches the submodule for you and populates the kubespray directory. Or
- Clone the GCS repo with `git clone --recurse-submodules https://github.com/gluster/gcs.git` or `git clone --recursive https://github.com/gluster/gcs.git`. This will download the kubespray submodule during the initial clone.

**Comment by JohnStrunk** [comment]
If this still isn't working, please re-open.
