### ISSUE TITLE
after killing a brick in gd2 pod, the pod restarts 

### ISSUE THREAD

**Issue by ksandha** [gluster/gcs#71]
1) Create a gcs cluster
2) Create a PVC of 2 gb
3) Login to gd2 pod 
4) Kill a brick from the volume.
5) Wait for some time the pod automatically restarts.

**Comment by Madhu-1** [comment]
may be related to https://github.com/gluster/glusterd2/issues/1321

**Comment by atinmu** [comment]
Fixed through https://github.com/gluster/glusterd2/issues/1321 .  Kindly retest.
